<a href="https://colab.research.google.com/github/edineim/machine_learning/blob/main/atividade.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


Importação de bibliotecas e criação repositorio no drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Aprendizado de Máquina/Atividades/EX-L05_manual-pipeline/date.csv')
df.head()

Id  Nascimento  MP  Gols  Assis.  G-PB  PB  PT  CrtsA  CrtV Pos.
0   1        1990  29     8       7     8   0   1      7     1   AT
1   2        1993  28    12       5    10   2   2      3     0   AT
2   3        1996  28     8       8     8   0   0      3     0   AT
3   4        1991  28     6       3     5   1   1      9     2   AT
4   5        1990  28     8       2     5   3   3      4     0   AT

Abertura de dados

In [ ]:
d = {'G': 0,'ZG': 1,'LT': 2,'LT,AT': 3,'AT': 4,'AT,LT': 5}

df['Pos.'] = df['Pos.'].map(d)
df.head()

Id  Nascimento  MP  Gols  Assis.  G-PB  PB  PT  CrtsA  CrtV  Pos.
0   1        1990  29     8       7     8   0   1      7     1     4
1   2        1993  28    12       5    10   2   2      3     0     4
2   3        1996  28     8       8     8   0   0      3     0     4
3   4        1991  28     6       3     5   1   1      9     2     4
4   5        1990  28     8       2     5   3   3      4     0     4

Conversão de caracteres em numeros, utilizando um dicionario como referencia

In [ ]:
X = df.iloc[:, 1:10].values
X

array([[1990,   29,    8, ...,    1,    7,    1],
       [1993,   28,   12, ...,    2,    3,    0],
       [1996,   28,    8, ...,    0,    3,    0],
       ...,
       [2000,   13,    0, ...,    0,    0,    0],
       [1992,   13,    0, ...,    0,    0,    0],
       [1993,   12,    1, ...,    0,    3,    0]])

Aprensentação das caracteristicas

In [ ]:
y = df['Pos.'].values
y

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1])

Aprensentação dos rotulos

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.20, shuffle=True, random_state=23, stratify=y)
np.bincount(y_train)

array([18, 75, 56, 17, 30, 33])

Divisão de elementos para 20% de teste e realizando o treinamento com 80%

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)
X_train_std = scaler.transform(X_train)
X_test_std = scaler.transform(X_test)
X_train_std

array([[ 0.6413789 ,  1.57869501,  0.20982378, ..., -0.24430558,
         2.14507367, -0.26673436],
       [-0.35777598, -1.09771447, -0.75761874, ..., -0.24430558,
         0.04224032, -0.26673436],
       [-0.35777598,  1.37281736, -0.75761874, ..., -0.24430558,
         0.04224032, -0.26673436],
       ...,
       [-0.10798726,  0.96106206, -0.75761874, ..., -0.24430558,
        -0.79889302, -0.26673436],
       [ 1.14095634,  1.37281736, -0.4351379 , ..., -0.24430558,
         1.724507  , -0.26673436],
       [ 1.39074506,  1.37281736, -0.11265706, ..., -0.24430558,
         0.46280699, -0.26673436]])

Normalização dos elementos

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=4)

knn_model.fit(X_train_std, y_train)

KNeighborsClassifier(n_neighbors=4)

Classificação com Knn definindo para 4 vizinhos

In [ ]:
y_pred = knn_model.predict(X_test_std)
print(y_pred)
print(y_test)

[1 4 4 1 2 5 1 1 1 5 1 4 1 2 0 2 0 5 4 1 2 5 1 1 1 2 2 0 5 1 1 2 2 1 5 0 3
 0 1 5 1 1 3 2 4 2 0 0 2 0 1 1 1 2 1 1 4 2]
[1 2 4 4 1 5 2 3 5 5 2 1 1 1 1 2 2 3 5 1 2 5 2 5 2 1 3 1 5 1 1 1 4 1 5 0 3
 2 1 4 2 1 4 4 3 2 0 2 1 0 0 1 2 2 4 1 4 1]


Aprensentação da classificação de elementos do conjunto de predição com o conjunto de teste

In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

0.43103448275862066

Avaliação de acurácia